php:
  build: .
  ports:
    - "84:80"
  volumes:
    - .:/var/www/html
  links:
    - db

db:
  image: mysql:8.0
  volumes:
    - /var/lib/mysql
    - ./dump:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=phproot
    - MYSQL_USER=usuario
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=voxus