version: "3.8"
services:
  www:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: payments
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/config:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - persistent:/var/lib/mysql
volumes:
  persistent: