version: "3.8"
services:
  www:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html/
    links:
      - db
    networks:
      - default

  db:
    image: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default
    # ports:
    #   - 5432:5432
  # db:
  #   image: mysql:8.0
  #   ports:
  #     - "3306:3306"
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_DATABASE: payments
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./mysql:/docker-entrypoint-initdb.d
  #     - ./mysql/config:/etc/mysql/conf.d
  #     - persistent:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - db:db
  #   ports:
  #     - 8000:80
  #   environment:
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - persistent:/var/lib/mysql
volumes:
  db-data: